# Arbeiten mit Tensors

Andreas Sünder

In [53]:
%%html
<style>
table {float:left}
</style>

## Grundlagen

In [54]:
import torch

In [55]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [56]:
b = torch.zeros(3)
b

tensor([0., 0., 0.])

In [57]:
a[1]

tensor(1.)

In [58]:
a[2] = 2.0
a

tensor([1., 1., 2.])

Tensor-Objekte lassen sich auch direkt über den Konstruktor initialisieren:

In [59]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [60]:
float(points[0]), float(points[1])

(4.0, 1.0)

Es sind auch zweidimensionale Tensors möglich:

In [61]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

Die Größe lässt sich über `tensor.shape` herausfinden:

In [62]:
points.shape

torch.Size([3, 2])

Zweidimensionale Arrays lassen sich auch über `zeros` oder `ones` erstellen:

In [63]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Diese Arrays lassen sich über ein oder zwei Indexes ansprechen:

In [64]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [65]:
points[0, 1]

tensor(1.)

In [66]:
points[0]

tensor([4., 1.])

## Datentypen

In PyTorch wurden eigene Datentypen definiert, die extra für das Arbeiten mit Tensors verwendet werden können:

|Data type|dtype|CPU tensor|GPU tensor|
|--- |--- |--- |--- |
|32-bit floating point|torch.float32  torch.floatat|torch.FloatTensor|torch.cuda.FloatTensor|
|64-bit floating point|torch.float64 or torch.double|torch.DoubleTensor|torch.cuda.DoubleTensor|
|16-bit floating point [1]|torch.float16 or torch.half|torch.HalfTensor|torch.cuda.HalfTensor|
|16-bit floating point [2]|torch.bfloat16|torch.BFloat16Tensor|torch.cuda.BFloat16Tensor|
|32-bit complex|torch.complex32 or torch.chalf|||
|64-bit complex|torch.complex64 or torch.cfloat|||
|128-bit complex|torch.complex128 or torch.cdouble|||
|8-bit integer (unsigned)|torch.uint8|torch.ByteTensor|torch.cuda.ByteTensor|
|8-bit integer (signed)|torch.int8|torch.CharTensor|torch.cuda.CharTensor|
|16-bit integer (signed)|torch.int16 or torch.short|torch.ShortTensor|torch.cuda.ShortTensor|
|32-bit integer (signed)|torch.int32 or torch.int|torch.IntTensor|torch.cuda.IntTensor|
|64-bit integer (signed)|torch.int64 or torch.long|torch.LongTensor|torch.cuda.LongTensor|
|Boolean|torch.bool|torch.BoolTensor|torch.cuda.BoolTensor|
|quantized 8-bit integer (unsigned)|torch.quint8|torch.ByteTensor|/|
|quantized 8-bit integer (signed)|torch.qint8|torch.CharTensor|/|
|quantized 32-bit integer (signed)|torch.qint32|torch.IntTensor|/|
|quantized 4-bit integer (unsigned) [3]|torch.quint4x2|torch.ByteTensor|/|

Möchte man bestimmte Datentypen verwenden, kann man diesen beim Erstellen von Tensors über das `dtype`-Argument angeben:

In [67]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

Über `Tensor.dtype` lässt sich der geseicherte Datentyp auslesen:*

In [68]:
short_points.dtype

torch.int16

Datentypen lassen sich auch umcasten:

In [69]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

# Alternativ über die to()-Methode:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

double_points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

Werden Operationen mit verschiedenen Datentypen durchgeführt, so werden diese (wo nötig) umgecastet:

In [70]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## Die Tensor-API

Viele Funktionen lassen sich über das `torch`-Modul oder auch über ein Tensor selbst aufrufen:

In [71]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

# Oder direkt übers Objekt:
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

<div class="alert alert-block alert-info"><b>TODO:</b> Ausprobieren weiterer Funktionen.</div>

## Tensors im Speicher

<div class="alert alert-block alert-info"><b>TODO:</b> Kommt noch... (hat sich für PyTorch 2.0 geändert)</div>

## Tensors und die GPU

Üblicherweise werden Tensors im RAM gespeichert. Möchte man diese stattdessen im VRAM ablegen, so kann man den `device`-Parameter verwenden:

In [72]:
points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device="cuda")

Bereits existierende Tensors können auch später in den VRAM geschoben werden:

In [73]:
points_gpu = points.to(device="cuda")

# oder bei mehreren GPUs mit Angabe eines Index:
points_gpu = points.to(device="cuda:0")

# oder kurzerhand:
points_gpu = points.cuda()
points_gpu = points.cuda(0)
points_cpu = points_gpu.cpu()

Wichtig zu beachten ist, dass ein auf die GPU geschobener Tensor auch dort bleibt, sofern er nicht manuell woanders hingeschoben wird.

## (De-)Serialisierung von Tensors

Tensors können auch als Datei für den späteren Gebrauch abgespeichert werden. Wichtig ist, dass nur PyTorch mit den abgespeicherten Dateien etwas anfangen kann:

In [74]:
# Speichern
torch.save(points, "./ourpoints.t")

# Laden
points = torch.load("./ourpoints.t")