# Arbeiten mit Tensors

Andreas Sünder

In [1]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [6]:
b = torch.zeros(3)
b

tensor([0., 0., 0.])

In [3]:
a[1]

tensor(1.)

In [4]:
a[2] = 2.0
a

tensor([1., 1., 2.])

Tensor-Objekte lassen sich auch direkt über den Konstruktor initialisieren:

In [5]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
float(points[0]), float(points[1])

(4.0, 1.0)

Es sind auch zweidimensionale Tensors möglich:

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

Die Größe lässt sich über `tensor.shape` herausfinden:

In [11]:
points.shape

torch.Size([3, 2])

Zweidimensionale Arrays lassen sich auch über `zeros` oder `ones` erstellen:

In [13]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

Diese Arrays lassen sich über ein oder zwei Indexes ansprechen:

In [15]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [16]:
points[0, 1]

tensor(1.)

In [17]:
points[0]

tensor([4., 1.])